# Generated by Django 3.1 on 2020-10-26 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbs',
            name='dislike',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='thumbs',
            name='like',
            field=models.IntegerField(blank=True),
        ),
    ]
