# Generated by Django 3.1 on 2020-10-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20201026_1344'),
    ]

    operations = [
        migrations.CreateModel(
            name='section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=400)),
                ('name', models.CharField(max_length=50)),
                ('time', models.TimeField(auto_now_add=True)),
            ],
        ),
    ]
