# Generated by Django 3.1 on 2020-10-28 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20201027_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='time',
            field=models.CharField(max_length=50),
        ),
    ]
